/* Light-quality probe for the iframe-backed Davis twin. Local adapter runs add ?debug and expose __DAVIS_TWIN_DEBUG__. */
import { execFileSync, spawn } from 'node:child_process';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const ROOT=process.cwd(),PORT=8983,DEBUG_PORT=9283;
const CHROME=['chromium','chromium-browser','google-chrome','google-chrome-stable'].find(c=>{try{execFileSync('which',[c],{stdio:'ignore'});return true}catch{return false}});
if(!CHROME){console.error('no chromium');process.exit(2)}
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.json':'application/json'};
const server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://x').pathname).replace(/^\/+/,''),file=path.join(ROOT,rel||'index.html');if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.statusCode=404;res.end('nf');return}res.setHeader('Content-Type',MIME[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))});await new Promise(r=>server.listen(PORT,r));
const profile=fs.mkdtempSync('/tmp/sc-lq-'),chrome=spawn(CHROME,['--headless','--no-sandbox','--disable-dev-shm-usage','--enable-gpu','--use-gl=angle','--use-angle=swiftshader-webgl','--enable-unsafe-swiftshader','--disable-gpu-sandbox','--enable-webgl','--ignore-gpu-blocklist',`--remote-debugging-port=${DEBUG_PORT}`,`--user-data-dir=${profile}`,'--window-size=1280,900'],{stdio:'ignore'});
let target;for(let i=0;i<40&&!target;i++){try{target=(await(await fetch(`http://127.0.0.1:${DEBUG_PORT}/json/list`)).json()).find(t=>t.type==='page')}catch{}await new Promise(r=>setTimeout(r,250))}if(!target)throw new Error('no CDP page');
const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map(),errors=[];
ws.onmessage=ev=>{const d=JSON.parse(ev.data);if(d.id&&pending.has(d.id)){pending.get(d.id)(d);pending.delete(d.id)}if(d.method==='Runtime.exceptionThrown')errors.push(d.params.exceptionDetails?.exception?.description||'exception');if(d.method==='Runtime.consoleAPICalled'&&d.params.type==='error')errors.push('console error')};
const send=(method,params={})=>new Promise((resolve,reject)=>{const i=++id;pending.set(i,resolve);ws.send(JSON.stringify({id:i,method,params}));setTimeout(()=>{if(pending.has(i)){pending.delete(i);reject(new Error('timeout'))}},20000)});
const ev=async expression=>{const d=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(d.result?.exceptionDetails)throw new Error(d.result.exceptionDetails.exception?.description||'eval error');return d.result.result.value};
await send('Page.enable');await send('Runtime.enable');await send('Page.navigate',{url:`http://127.0.0.1:${PORT}/index.html`});
let ok=false;for(let i=0;i<120&&!ok;i++){await new Promise(r=>setTimeout(r,500));ok=await ev(`!!window.__SC_CAMPUS_MAP_3D__?.ready&&!!window.__SC_CAMPUS_MAP_3D__?.frame?.contentWindow?.__DAVIS_TWIN_DEBUG__`)}if(!ok)throw new Error('twin debug probe not ready');
const result=await ev(`(async()=>{const m=window.__SC_CAMPUS_MAP_3D__,d=m.frame.contentWindow.__DAVIS_TWIN_DEBUG__;m.setWeather('clear');m.setTime('2026-06-21T12:00:00-04:00');d.updateEnv?.(0);d.renderer.render(d.scene,d.camera);const day=d.ST.night;const light=d.keyLight.intensity;m.setWeather('rain');d.updateEnv?.(.1);d.updatePrecip?.(.1);d.renderer.render(d.scene,d.camera);const rain=d.W.rain;m.setTime('2026-12-21T21:30:00-05:00');d.updateEnv?.(0);const night=d.ST.night;await m.frame.contentWindow.DavisTwin.drive();await new Promise(r=>setTimeout(r,500));const drivePacked=!!d.drive.packedCar,headlights=d.drive.packHeadMats?.length||0,taillights=d.drive.packTailMats?.length||0;await m.frame.contentWindow.DavisTwin.drive();return {day,light,rain,night,calls:d.renderer.info.render.calls,triangles:d.renderer.info.render.triangles,pr:d.renderer.getPixelRatio,environment:!!d.scene.environment,carAsset:d.ASSET_STATE.car,transitAssets:d.ASSET_STATE.transit,trafficMode:d.traffic?.mode,transitCount:d.transit?.vehicles?.length,drivePacked,headlights,taillights}})()`);
console.log('RESULT '+JSON.stringify(result));
if(!(result.light>0&&result.rain>.5&&result.night>.5&&result.calls>0&&result.triangles>0&&result.carAsset==='loaded'&&result.transitAssets.bus==='loaded'&&result.transitAssets.schoolBus==='loaded'&&result.trafficMode==='packed'&&result.transitCount===2&&result.drivePacked&&result.headlights>0&&result.taillights>0))process.exitCode=1;
if(errors.length){console.error('ERRORS '+JSON.stringify(errors.slice(0,5)));process.exitCode=1}else console.log('NO BROWSER ERRORS');
chrome.kill('SIGKILL');server.close();
